apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portworx-app-of-apps
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/haklein/argotest
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
